server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/7346874/springcloud.git
          searchPaths: config
          username: 7346874@qq.com
          password: yqz5201314..
      label: master
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/